# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  serviceBusLocation: 'Norway East'
  deploymentFile: 'azuredeploy_02.json'
  resourceGroupName: 'SPL_TST'
  subscriptionId: 'f8340282-4c2d-41e5-bc96-0a433f327610'
  resourceManagerConnection: 'splsolera'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Dev
  jobs:
  - job: Dev
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '${{variables.resourceManagerConnection}}'
        subscriptionId: '${{variables.subscriptionId}}'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{variables.resourceGroupName}}'
        location: '${{variables.serviceBusLocation}}'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/${{variables.deploymentFile}}'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/dev.azuredeploy.parameters.json'
        deploymentMode: 'Incremental'

- stage: Test
  jobs:
  - job: Test
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '${{variables.resourceManagerConnection}}'
        subscriptionId: '${{variables.subscriptionId}}'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{variables.resourceGroupName}}'
        location: '${{variables.location}}'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/${{variables.deploymentFile}}'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/test.azuredeploy.parameters.json'
        deploymentMode: 'Incremental'

- stage: Beta
  jobs:
  - job: Beta
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '${{variables.resourceManagerConnection}}'
        subscriptionId: '${{variables.subscriptionId}}'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{variables.resourceGroupName}}'
        location: '${{variables.serviceBusLocation}}'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/${{variables.deploymentFile}}'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/beta.azuredeploy.parameters.json'
        deploymentMode: 'Incremental'

- stage: Pat
  jobs:
  - job: Pat
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '${{variables.resourceManagerConnection}}'
        subscriptionId: '${{variables.subscriptionId}}'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{variables.resourceGroupName}}'
        location: '${{variables.serviceBusLocation}}'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/${{variables.deploymentFile}}'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/pat.azuredeploy.parameters.json'
        deploymentMode: 'Incremental'

- stage: Pre
  jobs:
  - job: Pre
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '${{variables.resourceManagerConnection}}'
        subscriptionId: '${{variables.subscriptionId}}'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{variables.resourceGroupName}}'
        location: '${{variables.serviceBusLocation}}'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/${{variables.deploymentFile}}'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/pre.azuredeploy.parameters.json'
        deploymentMode: 'Incremental'