# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  serviceBusLocation: 'Norway East'
  deploymentFile: 'azuredeploy_02.json'
  resourceGroupName: 'SPL_TST'
  subscriptionId: 'f8340282-4c2d-41e5-bc96-0a433f327610'
  resourceManagerConnection: 'spl-decision-support-cicd-prod'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Prod
  jobs:
  - job: Prod
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '${{variables.resourceManagerConnection}}'
        subscriptionId: '${{variables.subscriptionId}}'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{parameters.resourceGroupName}}'
        location: '${{parameters.serviceBusLocation}}'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/${{parameters.deploymentFile}}'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/prod.azuredeploy.parameters.json'
        deploymentMode: 'Incremental'