# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  serviceBusLocation: 'Norway East'
  deploymentFile: 'azuredeploy_02.json'
  resourceGroupName: 'DecisionSupport'
  subscriptionId: '26e2ddde-877d-449e-a869-60e0ac6fee92'
  resourceManagerConnection: 'decision-support-cicd-nonprod'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Dev
  jobs:
  - job: Dev
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '${{variables.resourceManagerConnection}}'
        subscriptionId: '${{variables.subscriptionId}}'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{variables.resourceGroupName}}'
        location: '${{variables.serviceBusLocation}}'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/${{variables.deploymentFile}}'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/dev.azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
