# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Prod
  jobs:
  - job: Prod
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'decision-support-cicd-prod'
        subscriptionId: '8a16b850-169e-41ed-abba-7619855ac2a4'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{parameters.resourceGroupName}}'
        location: 'UK South'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/azuredeploy.json'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/prod.azuredeploy.parameters.json'
        deploymentMode: 'Incremental'

- stage: Prod_DR
  jobs:
  - job: Prod_DR
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'decision-support-cicd-prod'
        subscriptionId: '8a16b850-169e-41ed-abba-7619855ac2a4'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'DecisionSupport-DR'
        location: 'UK West'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/azuredeploy_dr.json'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/Audatex.ArmTemplates/prod.azuredeploy.parameters.json'
        deploymentMode: 'Incremental'